### ISSUE TITLE
Ability to have events/notifications?

### ISSUE THREAD

**Issue by hufftheweevil** [gruijter/netgear.js#10]
I don't think the Genie app does any sort of events/reporting, so I pretty much know the answer here. But is there any way to build in events/notifications? For example, it would be nice to get an event when a particular device connects to the network. Or a new device, etc.

**Comment by gruijter** [comment]
netgear.js is meant to be a wrapper for the soap interface only. It does not keep a state of the router. But with netgear.js you can build your own application that keeps a list of connected devices, and produce an event on connect/disconnect of devices. Actually that is what I did myself for the Homey home automation platform: 

https://apps.athom.com/app/com.gruijter.netgear

So have fun building it :)
And when you share it on github and/or via npm, anyone can reuse your work.
