### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by roblandry** [gruijter/netgear.js#11]
I have no issues with your code, but would rather thank you for the work you have done. I have implemented the code you suggested over a year ago into a pynetgear_enhanced lib that works wonderfully with home assistant!

[Hass Post](https://community.home-assistant.io/t/netgear-enhanced-sensors-and-switches-for-router-controls/107266)
[Python Lib](https://gitlab.landry.me/Home-Assistant/pynetgear)
[Hass Components](https://gitlab.landry.me/Home-Assistant/netgear-enhanced-sensor)

**Comment by gruijter** [comment]
Super! Thanks for your acknowledgement :) 

I added some more soap commands since then, so go check them out!

But I do hope you can work together with the people of pynetgear, so that there is only 1 python version of the netgear lib to maintain and for people to use.

**Comment by solick** [comment]
hi @gruijter just want to let you know, that I used your code to create a Node-RED wrapper for easy use in Node-RED. Thanks for your effort. https://github.com/solick/node-red-contrib-netgear.git 
Will add more nodes for the different commands over the next few weeks.

**Comment by gruijter** [comment]
Awesome! Will give it a try this weekend. Thx 4 letting me know 🤗
