### ISSUE TITLE
All devices showing as 'wireless'

### ISSUE THREAD

**Issue by m1ckyb** [gruijter/netgear.js#15]
Hi Thanks for this,

Only have one issue i have found right now, using a Netgear MR60 all devices in getAttachedDevices() are showing as wireless

  AttachedDevice {
    ConnectionType: 'wireless',

Even though this device is showing as a Wired device in the app, any help would be appreciated, any info you might need i will attempt to get for you.

Thanks

**Comment by gruijter** [comment]
Can you post the result of a test here?
`npm test password`

**Comment by m1ckyb** [comment]
Testing now. Hang on.....
========== STARTING TEST ==========
Node version: v10.19.0
Netgear package version: 4.2.0
OS: linux 5.4.106-1-pve
t = 0
trying to auto discover Netgear routers...
[ { Firmware: 'V1.0.6.110',
    RegionTag: 'MR60_AU',
    Region: 'au',
    Model: 'MR60',
    InternetConnectionStatus: 'Up',
    OpenDNSEnabled: '0',
    SOAPVersion: '3.78',
    ReadyShareSupportedLevel: '0',
    XCloudSupported: '1',
    LoginMethod: '2.0',
    DeviceMode: '0',
    isBlankState: '0',
    host: '192.168.1.1',
    port: 80 },
  { Firmware: 'V1.0.6.110',
    RegionTag: 'MS60_AU',
    Region: 'au',
    Model: 'MS60',
    InternetConnectionStatus: 'Down',
    ParentalControlSupported: '0',
    CircleEnabled: '0',
    OpenDNSEnabled: '0',
    SOAPVersion: '3.58',
    ReadyShareSupportedLevel: '25',
    XCloudSupported: '0',
    LoginMethod: '2.0',
    DeviceMode: '0',
    host: '192.168.1.21',
    port: 80 } ]
t = 129.735
trying to login using method 1...
method 1 ok.
trying to login using method 2...
method 2 ok.
trying to login using auto method...
reported login method: 2
t = 134.179
trying to getInfo...
{ ModelName: 'MR60',
  Description: '802.11ac Dual Band Gigabit Wireless Router MR60',
  SerialNumber: '**********',
  SignalStrength: '100',
  Firmwareversion: 'V1.0.6.110',
  SmartAgentversion: '3.0',
  FirewallVersion: 'iptables v1.6.2',
  VPNVersion: 'N/A',
  OthersoftwareVersion: '2.0.49',
  Hardwareversion: 'MR60',
  Otherhardwareversion: 'N/A',
  FirstUseDate: 'Friday, 06 Nov 2020 19:00:15',
  DeviceName: 'MR60',
  FirmwareDLmethod: 'HTTPS',
  FirmwareLastUpdate: '2019_10.27_9:6:14',
  FirmwareLastChecked: '2019_10.27_9:6:14',
  DeviceMode: '0',
  DeviceModeCapability: '0',
  DeviceNameUserSet: 'false' }
t = 134.876
trying to getSystemInfo...
{ NewCPUUtilization: 0,
  NewPhysicalMemory: 256,
  NewMemoryUtilization: 53,
  NewPhysicalFlash: 128,
  NewAvailableFlash: 128 }
t = 135.228
trying to get supportFeatures...
{ WanAggregation: '1.0',
  NameNTGRDevice: '1.0',
  DynamicQoS: '1.0',
  MaxMonthlyTrafficLimitation: '4095000000',
  AccessControl: '1.0',
  SpeedTest: '2.0',
  BitDefenderSecurity: '1.0',
  DeviceTypeIcon: '2.1',
  TCAcceptance: '1.0',
  AttachedDevice: '2.0',
  DeviceTypeIdentification: '1.0',
  PasswordReset: '2.0',
  SupportXMLEncoded: '1.0',
  SupportAXMode: '1.0',
  SupportWPA3: '1.0',
  SatelliteInfoSatteliteInfo: '2.0',
  SupportNEWTC: '1.0',
  TimeZone: '2.0' }
t = 135.902
trying to get the LAN configuration...
{ NewLANSubnet: '255.255.255.0',
  NewWANLAN_Subnet_Match: '0',
  NewLANMACAddress: '100C6B351C83',
  NewLANIP: '192.168.1.1',
  NewDHCPEnabled: 'true' }
t = 135.91
trying to get the WAN configuration...
{ NewEnable: '1',
  NewConnectionType: 'PPPoE',
  NewExternalIPAddress: '***',
  NewSubnetMask: '255.255.255.255',
  NewAddressingType: 'PPPoE',
  NewDefaultGateway: '***',
  NewMACAddress: '***',
  NewMACAddressOverride: '0',
  NewMaxMTUSize: '1492',
  NewDNSEnabled: '0',
  NewDNSServers: '8.8.8.8 8.8.4.4' }
t = 136.259
trying to get the Traffic Meter Enabled Status...
Traffic Meter Enabled: true
t = 136.576
trying to get trafficMeter...
{ newTodayUpload: 7794,
  newTodayDownload: 35190,
  newMonthUpload: 143901,
  newMonthDownload: 802383 }
t = 137.243
trying to get the Traffic Meter Options...
{ newControlOption: 'No Limit',
  newNewMonthlyLimit: 0,
  restartHour: 0,
  restartMinute: 0,
  restartDay: 1 }
t = 137.584
trying to get System Uptime (hh:mm:ss)...
 2 days 22:49:50
t = 138.257
trying to get the Device configuration...
{ BlankState: '0',
  NewBlockSiteEnable: '0',
  NewBlockSiteName: undefined,
  NewTimeZone: '+10',
  NewDaylightSaving: '0' }
t = 138.598
trying to get Parental Control Status...
Parental Control Enabled: true
t = 140.781
trying to get Qos Status...
Qos Enabled: false
t = 140.819
trying to get Qos Bandwidth options...
{ newUplinkBandwidth: 0, newDownlinkBandwidth: 0, enabled: 2 }
t = 141.121
trying to get available and selected WiFi channels...
Available channels 2.4G-1: Auto,1,2,3,4,5,6,7,8,9,10,11,12,13
selected channel 2.4G-1: Auto
Available channels 5.0G-1: 36,40,44,48,149,153,157,161
selected channel 5.0G-1: 44
Available channels 5.0G-2: 36,40,44,48,149,153,157,161
5.0G-2 channel is not available
t = 143.478
trying to get Smart Connect Status...
404 Not Found. The requested function/page is not available
Smart Connect Enabled: [object Object]
t = 144.485
trying to get router logs...
last log: [DHCP IP: (192.168.1.189)] to MAC address 30:C9:AB:7E:4A:F5, Monday, May 17,2021 22:01:17
t = 154.295
trying to get Guest Wifi Status...
2.4G-1 Guest wifi enabled: false
5.0G-1 Guest wifi enabled: false, method: 1
5.0G-2 Guest wifi is not available
t = 155.633
trying to get Device Access Control Status...
Block Device Enabled: true
t = 155.973
trying to get attachedDevices method 1...
Number of attached devices: 58
First attached device:
AttachedDevice {
  IP: '192.168.1.2',
  Name: '',
  NameUserSet: undefined,
  MAC: '***',
  ConnectionType: 'wireless',
  SSID: undefined,
  Linkspeed: 141,
  SignalStrength: 54,
  AllowOrBlock: 'Allow',
  Schedule: undefined,
  DeviceType: undefined,
  DeviceTypeV2: undefined,
  DeviceTypeUserSet: undefined,
  DeviceTypeName: undefined,
  DeviceTypeNameV2: undefined,
  DeviceModel: undefined,
  DeviceModelUserSet: undefined,
  Upload: undefined,
  Download: undefined,
  QosPriority: undefined,
  Grouping: undefined,
  SchedulePeriod: undefined,
  ConnAPMAC: undefined }
t = 161.841
trying to get attachedDevices method 2...
Number of attached devices: 58
First attached device:
{ IP: '192.168.1.2',
  Name: 'ITON Technology',
  NameUserSet: false,
  MAC: '***',
  ConnectionType: '2.4GHz',
  SSID: 'Compu-Global-Hyper-Mega-Net',
  Linkspeed: 141,
  SignalStrength: 53,
  AllowOrBlock: 'Allow',
  Schedule: false,
  DeviceType: 24,
  DeviceTypeUserSet: false,
  DeviceTypeV2: 6,
  DeviceTypeNameV2: 'Media Streamer',
  Upload: 0,
  Download: 0,
  QosPriority: 1,
  DeviceModelUserSet: false,
  DeviceModel: undefined,
  Grouping: 0,
  SchedulePeriod: 0,
  ConnAPMAC: '***' }
t = 162.672
trying to check newFirmware...
check newFirmware method: 2
{ currentVersion: '1.0.6.110', newVersion: '', releaseNote: '' }
t = 168.217
trying to logout...
NetgearRouter {
  host: '192.168.1.1',
  port: 80,
  tls: false,
  username: 'admin',
  password: '*****',
  timeout: 18000,
  sessionId: '***',
  cookie: true,
  loggedIn: false,
  configStarted: true,
  soapVersion: 3,
  loginMethod: 2,
  getAttachedDevicesMethod: 2,
  checkNewFirmwareMethod: 2,
  guestWifiMethod: { set24_1: undefined, get50_1: 1, set50_1: undefined },
  lastResponse: '...',
  queue:
   SmartQueue {
     queue: Map {},
     overheat: 1621252736649,
     pending: false,
     params:
      { default: [Object],
        rules: [Object],
        overall: [Object],
        retryTime: 2,
        ignoreOverallOverheat: true },
     heatPart: 100 } }
t = 168.556
test finished with 1 errors

**Comment by gruijter** [comment]
The device on 192.168.1.2 is reported by the router as wireless. Is this not correct?

```
ConnectionType: '2.4GHz',
SSID: 'Compu-Global-Hyper-Mega-Net',
```

Note: If you do getAttachedDevices(2) you will probably get more detailed info then when using getAttachedDevices().

**Comment by m1ckyb** [comment]
Thanks, using getAttachedDevices(2) a actually shows wired.. SHould of looked at that better

But using getAttachedDevices(1) is showing as wireless, not much as a problem I will just use (2) to get the data i need

Thanks again, this is a really useful app.. :)
