### ISSUE TITLE
"Not logged in error" after an amount of time.

### ISSUE THREAD

**Issue by vioxxide** [gruijter/netgear.js#16]
Hello. Thank you for the library. I'm having an issue. I'm basically using your example code as posted... and it will work a while but then suddenly (and without any explanation that I have been able to locate) I'll start getting "Error: Not logged in." I can log in thru 192.168.1.1 just fine and as I said it does work for a while it just stops working and throwing this error everytime. Even if i restart my node.js server. I'm not sure if the router is blocking me for too many requests? I can't think of any other reason to explain this behavior. Any suggestions would be greatly appreciated. Thank you so much!

const netgearRouter = require('netgear');

async function getAttachedDevices() {
    try {
        let router = new netgearRouter();

        // Get router type, soap version, firmware version and internet connection status without login
        //const currentSetting = await router.getCurrentSetting();
        //console.log(currentSetting);

        // for other methods you first need to be logged in. Passing options will override previous settings
        const options = {
            password: '<verified correct password>',	// Password can also be passed during login
            host: '192.168.1.1',	// Autodiscovery will be performed when left out
            port: 5000,	// SOAP port. Autodiscovery will be performed when left out
            tls: false,	// TLS/SSL (HTTPS) is only supported on certain router types
        }

        console.log("before await");
        console.log(Date.now());

        await router.login(options);

        console.log("after await");
        console.log(Date.now());        // 12-20 milliseconds usually difference
        
       // get a list of attached devices
        const attachedDevices = await router.getAttachedDevices();
          
        return attachedDevices;
        
    }	catch (error) {
        console.log(error);    // "Error: Not logged in"
    }
}

**Comment by gruijter** [comment]
Maybe the session expires after 4 hours. If you simply login again after a fail does it work? Or are you locked out for a certain time.

And can you post the result of a test here?

npm test password

**Comment by vioxxide** [comment]
Hi. Thank you for your reply. It gets to the point where i can't log in thru the library at all. Even today. I can log in thru the router web console (192.168.1.1) with the same password. I had this happen before as I was playing with the code and it somehow reset and I was able to log in yesterday for an hour or so. Eventually I get the "not logged in error." I thought it was maybe that the router had rebooted but i checked the router log and it says it hasn't rebooted in over a week. So I'm not sure what reset the state that I regained the ability to log in. I can easily see this as having been caused by too many logins. I'm not sure if i should just log in and not log out and just keep that connection open? I did try that before but this still seemed to happen. Here is the result of the npm test. I went into node_modules and found this script. Hope it is the correct one to have run.

NetgearRouter {
  host: '192.168.1.1',
  port: 5000,
  tls: false,
  username: 'admin',
  password: '*****',
  timeout: 18000,
  sessionId: 'A7D88AE69687E58D9A00',
  cookie: undefined,
  loggedIn: false,
  configStarted: false,
  soapVersion: 3,
  loginMethod: 2,
  getAttachedDevicesMethod: undefined,
  checkNewFirmwareMethod: undefined,
  guestWifiMethod: { set24_1: undefined, get50_1: undefined, set50_1: undefined },
  lastResponse: '<?xml version="1.0" encoding="UTF-8"?>\r\n' +
    '<soap-env:Envelope\r\n' +
    '        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"\r\n' +
    '        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"\r\n' +
    '        >\r\n' +
    '<soap-env:Body>\r\n' +
    '    <m:SOAPLoginResponse\r\n' +
    '        xmlns:m="urn:NETGEAR-ROUTER:service:DeviceConfig:1">\r\n' +
    '    </m:SOAPLoginResponse>\r\n' +
    '    <ResponseCode>401</ResponseCode>\r\n' +
    '</soap-env:Body>\r\n' +
    '</soap-env:Envelope>\r\n',
  queue: SmartQueue {
    queue: Map(1) { 1626973202387 => [Object] },
    overheat: 1626973198892,
    pending: true,
    params: {
      default: [Object],
      rules: [Object],
      overall: [Object],
      retryTime: 2,
      ignoreOverallOverheat: true
    },
    heatPart: 100
  }
}

**Comment by gruijter** [comment]
Try rebooting your router (power off, wait 20s, power on) and rerun the test. I need to see what it says when it does login.

**Comment by vioxxide** [comment]
Hi. Thanks again. I reads the source for test.js and saw I needed to supply the password. Here is the updated test result: 
NetgearRouter {
  host: '192.168.1.1',
  port: 5000,
  tls: false,
  username: 'admin',
  password: '*****',
  timeout: 18000,
  sessionId: 'A7D88AE69687E58D9A00',
  cookie: true,
  loggedIn: true,
  configStarted: false,
  soapVersion: 3,
  loginMethod: 2,
  getAttachedDevicesMethod: 2,
  checkNewFirmwareMethod: 1,
  guestWifiMethod: { set24_1: undefined, get50_1: 1, set50_1: undefined },
  lastResponse: '...',
  queue: SmartQueue {
    queue: Map(0) {},
    overheat: 1626973965267,
    pending: false,
    params: {
      default: [Object],
      rules: [Object],
      overall: [Object],
      retryTime: 2,
      ignoreOverallOverheat: true
    },
    heatPart: 100
  }
}
t = 33.065
test finished with 6 errors

**Comment by vioxxide** [comment]
Just re-ran after reboot: NetgearRouter {
  host: '192.168.1.1',
  port: 5000,
  tls: false,
  username: 'admin',
  password: '*****',
  timeout: 18000,
  sessionId: 'A7D88AE69687E58D9A00',
  cookie: true,
  loggedIn: true,
  configStarted: false,
  soapVersion: 3,
  loginMethod: 2,
  getAttachedDevicesMethod: 2,
  checkNewFirmwareMethod: 1,
  guestWifiMethod: { set24_1: undefined, get50_1: 1, set50_1: undefined },
  lastResponse: '...',
  queue: SmartQueue {
    queue: Map(0) {},
    overheat: 1626974317177,
    pending: false,
    params: {
      default: [Object],
      rules: [Object],
      overall: [Object],
      retryTime: 2,
      ignoreOverallOverheat: true
    },
    heatPart: 100
  }
}
t = 35.099
test finished with 6 errors

**Comment by vioxxide** [comment]
Ok. I realized I coudln't log in thru genie so it made me think that Soap access had been blocked so I went ahead and did a factory reset. Also I realized I hadn't been going back in the console far enough. I think this might have the information that was missing:


========== STARTING TEST ==========
Node version: v15.7.0
Netgear package version: 4.3.2
OS: win32 10.0.19043
t = 0
trying to auto discover Netgear routers...
[
  {
    Firmware: 'V1.0.11.110_10.2.100',
    RegionTag: 'R7000_NA',
    Region: 'us',
    Model: 'R7000',
    InternetConnectionStatus: 'Up',
    ParentalControlSupported: '1',
    CircleEnabled: '0',
    OpenDNSEnabled: '0',
    SOAPVersion: '3.21',
    LoginMethod: '2.0',
    ReadyShareSupportedLevel: '29',
    XCloudSupported: '1',
    DeviceMode: '0',
    host: '192.168.1.1',
    port: 5000
  }
]
t = 2.102
trying to login using method 1...
method 1 ok.
trying to login using method 2...
method 2 ok.
trying to login using auto method...
reported login method: 2
t = 2.989
trying to getInfo...
{
  ModelName: 'R7000',
  Description: 'Netgear Smart Wizard 3.0, specification 0.7 version',
  SerialNumber: '**********',
  Firmwareversion: 'V1.0.11.110',
  SmartAgentversion: '3.0',
  FirewallVersion: 'ACOS NAT-Netfilter v3.0.0.5 (Linux Cone NAT Hot Patch 06/11/2010)',
  VPNVersion: 'N/A',
  OthersoftwareVersion: '10.2.100',
  Hardwareversion: 'R7000',
  Otherhardwareversion: 'N/A',
  FirstUseDate: 'Thursday, 22 Jul 2021 10:31:00',
  DeviceName: 'R7000',
  FirmwareDLmethod: 'Null',
  FirmwareLastUpdate: 'Null',
  FirmwareLastChecked: 'Null',
  DeviceMode: '0'
}
t = 3.502
trying to getSystemInfo...
{
  NewCPUUtilization: 33,
  NewPhysicalMemory: 256,
  NewMemoryUtilization: 59,
  NewPhysicalFlash: 128,
  NewAvailableFlash: 128
}
t = 3.702
trying to get supportFeatures...
{
  DynamicQoS: '1.0',
  OpenDNSParentalControl: '1.0',
  CircleParentalControl: '2.0',
  MaxMonthlyTrafficLimitation: '4095000000',
  AccessControl: '1.0',
  SpeedTest: '2.0',
  BitDefenderSecurity: '1.0',
  GuestNetworkSchedule: '1.0',
  TCAcceptance: '1.0',
  SmartConnect: '2.0',
  AttachedDevice: '2.0',
  NameNTGRDevice: '1.0',
  DeviceTypeIcon: '2.1',
  PasswordReset: '2.0'
}
t = 4.028
trying to get the LAN configuration...
{
  NewLANSubnet: '255.255.255.0',
  NewWANLAN_Subnet_Match: '1',
  NewLANMACAddress: '2C3033EB406A',
  NewLANIP: '192.168.1.1',
  NewDHCPEnabled: 'true'
}
t = 4.752
trying to get the WAN configuration...
{
  NewEnable: '1',
  NewConnectionType: 'DHCP',
  NewExternalIPAddress: '71.190.153.84',
  NewSubnetMask: '255.255.255.0',
  NewAddressingType: 'DHCP',
  NewDefaultGateway: '71.190.153.1',
  NewMACAddress: 'A0CEC8519DDA',
  NewMACAddressOverride: '1',
  NewMaxMTUSize: '1500',
  NewDNSEnabled: '1',
  NewDNSServers: '68.237.161.12 71.243.0.12 '
}
t = 5.185
trying to get the Traffic Meter Enabled Status...
Traffic Meter Enabled: false
t = 5.619
trying to get trafficMeter...
{
  newTodayUpload: 0,
  newTodayDownload: 0,
  newMonthUpload: 0,
  newMonthDownload: 0
}
t = 8.418
trying to get the Traffic Meter Options...
{
  newControlOption: 'No Limit',
  newNewMonthlyLimit: 0,
  restartHour: 0,
  restartMinute: 0,
  restartDay: 1
}
t = 8.461
trying to get System Uptime (hh:mm:ss)...
00:42:49
t = 8.801
trying to get the Device configuration...
{
  BlankState: '0',
  NewBlockSiteEnable: '0',
  NewBlockSiteName: undefined,
  NewTimeZone: '-04',
  NewDaylightSaving: '0'
}
t = 9.149
trying to get Parental Control Status...
Parental Control Enabled: false
t = 10.301
trying to get Qos Status...
Qos Enabled: false
t = 10.548
trying to get Qos Bandwidth options...
{ newUplinkBandwidth: 0, newDownlinkBandwidth: 0, enabled: 2 }
t = 10.926
trying to get available and selected WiFi channels...
Available channels 2.4G-1: Auto,1,2,3,4,5,6,7,8,9,10,11
selected channel 2.4G-1: Auto
Available channels 5.0G-1: 36,40,44,48,149,153,157,161
selected channel 5.0G-1: 153
Available channels 5.0G-2: 36,40,44,48,149,153,157,161
5.0G-2 channel is not available
t = 12.898
trying to get Smart Connect Status...
Smart Connect Enabled: false
t = 13.989
trying to get router logs...
socket hang up
{
  lastResponse: Error: socket hang up
      at connResetException (node:internal/errors:642:14)
      at Socket.socketOnEnd (node:_http_client:486:23)
      at Socket.emit (node:events:391:22)
      at endReadableNT (node:internal/streams/readable:1307:12)
      at processTicksAndRejections (node:internal/process/task_queues:81:21) {
    code: 'ECONNRESET'
  }
}
last log: undefined
t = 14.281
trying to get Guest Wifi Status...
2.4G-1 Guest wifi is not available
5.0G-1 Guest wifi is not available, method: 1
5.0G-2 Guest wifi is not available
t = 22.766
trying to get Device Access Control Status...
connect ECONNREFUSED 192.168.1.1:5000
{
  lastResponse: Error: connect ECONNREFUSED 192.168.1.1:5000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1139:16) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.1.1',
    port: 5000
  }
}
Block Device Enabled: [object Object]
t = 24.794
trying to get attachedDevices method 1...
connect ECONNREFUSED 192.168.1.1:5000
{
  lastResponse: Error: connect ECONNREFUSED 192.168.1.1:5000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1139:16) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.1.1',
    port: 5000
  }
}
Number of attached devices: undefined
First attached device:
undefined
t = 26.865
trying to get attachedDevices method 2...
connect ECONNREFUSED 192.168.1.1:5000
{
  lastResponse: Error: connect ECONNREFUSED 192.168.1.1:5000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1139:16) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.1.1',
    port: 5000
  }
}
Number of attached devices: undefined
First attached device:
undefined
t = 28.915
trying to check newFirmware...
connect ECONNREFUSED 192.168.1.1:5000
{
  lastResponse: Error: connect ECONNREFUSED 192.168.1.1:5000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1139:16) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.1.1',
    port: 5000
  }
}
check newFirmware method: 1
{}
t = 33.012
trying to logout...
connect ECONNREFUSED 192.168.1.1:5000
{
  lastResponse: Error: connect ECONNREFUSED 192.168.1.1:5000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1139:16) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '192.168.1.1',
    port: 5000
  }
}
NetgearRouter {
  host: '192.168.1.1',
  port: 5000,
  tls: false,
  username: 'admin',
  password: '*****',
  timeout: 18000,
  sessionId: 'A7D88AE69687E58D9A00',
  cookie: true,
  loggedIn: true,
  configStarted: false,
  soapVersion: 3,
  loginMethod: 2,
  getAttachedDevicesMethod: 2,
  checkNewFirmwareMethod: 1,
  guestWifiMethod: { set24_1: undefined, get50_1: 1, set50_1: undefined },
  lastResponse: '...',
  queue: SmartQueue {
    queue: Map(0) {},
    overheat: 1626979296924,
    pending: false,
    params: {
      default: [Object],
      rules: [Object],
      overall: [Object],
      retryTime: 2,
      ignoreOverallOverheat: true
    },
    heatPart: 100
  }
}
t = 35.095
test finished with 6 errors

**Comment by gruijter** [comment]
Yes indeed that was what I wanted to see. So this test was run right after a power cycle? Even halfway through this test the session fails (hence the errors).

I actually originally developed the package for the R7000. But I dont have that unit anymore. Maybe the newer firmware makes the soap interface unstable. I don't know how to solve this. I did see there is a newer fw release available. You could try that.

Also I see it started failing after trying to get the router logs. So you could maybe erase the logs and see if that helps. Or remove the log retrieval from the test and terun it.

**Comment by vioxxide** [comment]
Thank you for the time you have spent on this. I just installed 5/27/21 - Firmware update 1.0.11.123 Hot Fix. Now when I run the test I get 401 errors. I wonder if I tried from another device if it would work. Like the router blacklisted my MAC address. Although i can log in with Genie and Circle which uses the same SOAP API i believe.

Testing now. Hang on.....
========== STARTING TEST ==========
Node version: v15.7.0
Netgear package version: 4.3.2
OS: win32 10.0.19043
t = 0
trying to auto discover Netgear routers...
[
  {
    Firmware: 'V1.0.11.123_10.2.100',
    RegionTag: 'R7000_NA',
    Region: 'us',
    Model: 'R7000',
    InternetConnectionStatus: 'Up',
    ParentalControlSupported: '1',
    CircleEnabled: '0',
    OpenDNSEnabled: '0',
    SOAPVersion: '3.21',
    LoginMethod: '2.0',
    ReadyShareSupportedLevel: '29',
    XCloudSupported: '1',
    DeviceMode: '0',
    host: '192.168.1.1',
    port: 5000
  }
]
t = 2.089
trying to login using method 1...
method 1 ok.
trying to login using method 2...
method 2 ok.
trying to login using auto method...
reported login method: 2
t = 2.92
trying to getInfo...
401 Unauthorized. Incorrect password?
{
  lastResponse: '<?xml version="1.0" encoding="UTF-8"?>\r\n' +
    '<soap-env:Envelope\r\n' +
    '        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"\r\n' +
    '        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"\r\n' +
    '        >\r\n' +
    '<soap-env:Body>\r\n' +
    '    <ResponseCode>401</ResponseCode>\r\n' +
    '</soap-env:Body>\r\n' +
    '</soap-env:Envelope>\r\n'
}
trying to login again...
{ SerialNumber: '**********' }
t = 3.585
trying to getSystemInfo...
401 Unauthorized. Incorrect password?
{
  lastResponse: '<?xml version="1.0" encoding="UTF-8"?>\r\n' +
    '<soap-env:Envelope\r\n' +
    '        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"\r\n' +
    '        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"\r\n' +
    '        >\r\n' +
    '<soap-env:Body>\r\n' +
    '    <ResponseCode>401</ResponseCode>\r\n' +
    '</soap-env:Body>\r\n' +
    '</soap-env:Envelope>\r\n'
}
trying to login again...
{}
t = 4.261
trying to get supportFeatures...
401 Unauthorized. Incorrect password?
{
  lastResponse: '<?xml version="1.0" encoding="UTF-8"?>\r\n' +
    '<soap-env:Envelope\r\n' +
    '        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"\r\n' +
    '        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"\r\n' +
    '        >\r\n' +
    '<soap-env:Body>\r\n' +
    '    <ResponseCode>401</ResponseCode>\r\n' +
    '</soap-env:Body>\r\n' +
    '</soap-env:Envelope>\r\n'
}
trying to login again...
{}
t = 4.944
trying to get the LAN configuration...
401 Unauthorized. Incorrect password?
{
  lastResponse: '<?xml version="1.0" encoding="UTF-8"?>\r\n' +
    '<soap-env:Envelope\r\n' +
    '        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"\r\n' +
    '        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"\r\n' +
    '        >\r\n' +
    '<soap-env:Body>\r\n' +
    '    <ResponseCode>401</ResponseCode>\r\n' +
    '</soap-env:Body>\r\n' +
    '</soap-env:Envelope>\r\n'
}
trying to login again...
{}
t = 5.64
trying to get the WAN configuration...
401 Unauthorized. Incorrect password?
{
  lastResponse: '<?xml version="1.0" encoding="UTF-8"?>\r\n' +
    '<soap-env:Envelope\r\n' +
    '        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"\r\n' +
    '        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"\r\n' +
    '        >\r\n' +
    '<soap-env:Body>\r\n' +
    '    <ResponseCode>401</ResponseCode>\r\n' +
    '</soap-env:Body>\r\n' +
    '</soap-env:Envelope>\r\n'
}
trying to login again...
{}
t = 6.336
trying to get the Traffic Meter Enabled Status...
401 Unauthorized. Incorrect password?
{
  lastResponse: '<?xml version="1.0" encoding="UTF-8"?>\r\n' +
    '<soap-env:Envelope\r\n' +
    '        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"\r\n' +
    '        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"\r\n' +
    '        >\r\n' +
    '<soap-env:Body>\r\n' +
    '    <ResponseCode>401</ResponseCode>\r\n' +
    '</soap-env:Body>\r\n' +
    '</soap-env:Envelope>\r\n'
}
trying to login again...
Traffic Meter Enabled: [object Object]
t = 7.005
trying to get trafficMeter...
401 Unauthorized. Incorrect password?
{
  lastResponse: '<?xml version="1.0" encoding="UTF-8"?>\r\n' +
    '<soap-env:Envelope\r\n' +
    '        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"\r\n' +
    '        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"\r\n' +
    '        >\r\n' +
    '<soap-env:Body>\r\n' +
    '    <ResponseCode>401</ResponseCode>\r\n' +
    '</soap-env:Body>\r\n' +
    '</soap-env:Envelope>\r\n'
}
trying to login again...
{}
t = 7.702
trying to get the Traffic Meter Options...
401 Unauthorized. Incorrect password?
{
  lastResponse: '<?xml version="1.0" encoding="UTF-8"?>\r\n' +
    '<soap-env:Envelope\r\n' +
    '        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"\r\n' +
    '        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"\r\n' +
    '        >\r\n' +
    '<soap-env:Body>\r\n' +
    '    <ResponseCode>401</ResponseCode>\r\n' +
    '</soap-env:Body>\r\n' +
    '</soap-env:Envelope>\r\n'
}
trying to login again...
{}
t = 8.386
trying to get System Uptime (hh:mm:ss)...
401 Unauthorized. Incorrect password?
{
  lastResponse: '<?xml version="1.0" encoding="UTF-8"?>\r\n' +
    '<soap-env:Envelope\r\n' +
    '        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"\r\n' +
    '        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"\r\n' +
    '        >\r\n' +
    '<soap-env:Body>\r\n' +
    '    <ResponseCode>401</ResponseCode>\r\n' +
    '</soap-env:Body>\r\n' +
    '</soap-env:Envelope>\r\n'
}
trying to login again...
{}
t = 9.081
trying to get the Device configuration...
401 Unauthorized. Incorrect password?
{
  lastResponse: '<?xml version="1.0" encoding="UTF-8"?>\r\n' +
    '<soap-env:Envelope\r\n' +
    '        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"\r\n' +
    '        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"\r\n' +
    '        >\r\n' +
    '<soap-env:Body>\r\n' +
    '    <ResponseCode>401</ResponseCode>\r\n' +
    '</soap-env:Body>\r\n' +
    '</soap-env:Envelope>\r\n'
}
trying to login again...
{}
t = 10.143
trying to get Parental Control Status...
Config started error: Error: 401 Unauthorized. Incorrect password?
{
  lastResponse: '<?xml version="1.0" encoding="UTF-8"?>\r\n' +
    '<soap-env:Envelope\r\n' +
    '        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"\r\n' +
    '        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"\r\n' +
    '        >\r\n' +
    '<soap-env:Body>\r\n' +
    '    <ResponseCode>401</ResponseCode>\r\n' +
    '</soap-env:Body>\r\n' +
    '</soap-env:Envelope>\r\n'
}
trying to login again...
Parental Control Enabled: [object Object]
t = 10.867
trying to get Qos Status...
401 Unauthorized. Incorrect password?
{
  lastResponse: '<?xml version="1.0" encoding="UTF-8"?>\r\n' +
    '<soap-env:Envelope\r\n' +
    '        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"\r\n' +
    '        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"\r\n' +
    '        >\r\n' +
    '<soap-env:Body>\r\n' +
    '    <ResponseCode>401</ResponseCode>\r\n' +
    '</soap-env:Body>\r\n' +
    '</soap-env:Envelope>\r\n'
}
trying to login again...
Qos Enabled: [object Object]
t = 11.486
trying to get Qos Bandwidth options...
401 Unauthorized. Incorrect password?
{
  lastResponse: '<?xml version="1.0" encoding="UTF-8"?>\r\n' +
    '<soap-env:Envelope\r\n' +
    '        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"\r\n' +
    '        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"\r\n' +
    '        >\r\n' +
    '<soap-env:Body>\r\n' +
    '    <ResponseCode>401</ResponseCode>\r\n' +
    '</soap-env:Body>\r\n' +
    '</soap-env:Envelope>\r\n'
}
trying to login again...
{}
t = 12.174
trying to get available and selected WiFi channels...
2.4G-1 channels are not available
2.4G-1 channel is not available
5.0G-1 channels are not available
5.0G-1 channel is not available
5.0G-2 channels are not available
5.0G-2 channel is not available
t = 14.176
trying to get Smart Connect Status...
Config started error: Error: Not logged in
{
  lastResponse: '<?xml version="1.0" encoding="UTF-8"?>\r\n' +
    '<soap-env:Envelope\r\n' +
    '        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"\r\n' +
    '        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"\r\n' +
    '        >\r\n' +
    '<soap-env:Body>\r\n' +
    '    <ResponseCode>401</ResponseCode>\r\n' +
    '</soap-env:Body>\r\n' +
    '</soap-env:Envelope>\r\n'
}
trying to login again...
Smart Connect Enabled: [object Object]
t = 14.906
trying to get router logs...
401 Unauthorized. Incorrect password?
{
  lastResponse: '<?xml version="1.0" encoding="UTF-8"?>\r\n' +
    '<soap-env:Envelope\r\n' +
    '        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"\r\n' +
    '        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"\r\n' +
    '        >\r\n' +
    '<soap-env:Body>\r\n' +
    '    <ResponseCode>401</ResponseCode>\r\n' +
    '</soap-env:Body>\r\n' +
    '</soap-env:Envelope>\r\n'
}
trying to login again...
last log: undefined
t = 15.591
trying to get Guest Wifi Status...
2.4G-1 Guest wifi is not available
5.0G-1 Guest wifi is not available, method: 1
5.0G-2 Guest wifi is not available
t = 16.904
trying to get Device Access Control Status...
Not logged in
{
  lastResponse: '<?xml version="1.0" encoding="UTF-8"?>\r\n' +
    '<soap-env:Envelope\r\n' +
    '        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"\r\n' +
    '        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"\r\n' +
    '        >\r\n' +
    '<soap-env:Body>\r\n' +
    '    <ResponseCode>401</ResponseCode>\r\n' +
    '</soap-env:Body>\r\n' +
    '</soap-env:Envelope>\r\n'
}
trying to login again...
Block Device Enabled: [object Object]
t = 17.619
trying to get attachedDevices method 1...
401 Unauthorized. Incorrect password?
{
  lastResponse: '<?xml version="1.0" encoding="UTF-8"?>\r\n' +
    '<soap-env:Envelope\r\n' +
    '        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"\r\n' +
    '        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"\r\n' +
    '        >\r\n' +
    '<soap-env:Body>\r\n' +
    '    <ResponseCode>401</ResponseCode>\r\n' +
    '</soap-env:Body>\r\n' +
    '</soap-env:Envelope>\r\n'
}
trying to login again...
Number of attached devices: undefined
First attached device:
undefined
t = 18.321
trying to get attachedDevices method 2...
401 Unauthorized. Incorrect password?
{
  lastResponse: '<?xml version="1.0" encoding="UTF-8"?>\r\n' +
    '<soap-env:Envelope\r\n' +
    '        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"\r\n' +
    '        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"\r\n' +
    '        >\r\n' +
    '<soap-env:Body>\r\n' +
    '    <ResponseCode>401</ResponseCode>\r\n' +
    '</soap-env:Body>\r\n' +
    '</soap-env:Envelope>\r\n'
}
trying to login again...
Number of attached devices: undefined
First attached device:
undefined
t = 18.995
trying to check newFirmware...
Not logged in
{
  lastResponse: '<?xml version="1.0" encoding="UTF-8"?>\r\n' +
    '<soap-env:Envelope\r\n' +
    '        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"\r\n' +
    '        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"\r\n' +
    '        >\r\n' +
    '<soap-env:Body>\r\n' +
    '    <ResponseCode>401</ResponseCode>\r\n' +
    '</soap-env:Body>\r\n' +
    '</soap-env:Envelope>\r\n'
}
trying to login again...
check newFirmware method: 1
{}
t = 20.132
trying to logout...
401 Unauthorized. Incorrect password?
{
  lastResponse: '<?xml version="1.0" encoding="UTF-8"?>\r\n' +
    '<soap-env:Envelope\r\n' +
    '        xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"\r\n' +
    '        soap-env:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"\r\n' +
    '        >\r\n' +
    '<soap-env:Body>\r\n' +
    '    <ResponseCode>401</ResponseCode>\r\n' +
    '</soap-env:Body>\r\n' +
    '</soap-env:Envelope>\r\n'
}
trying to login again...
NetgearRouter {
  host: '192.168.1.1',
  port: 5000,
  tls: false,
  username: 'admin',
  password: '*****',
  timeout: 18000,
  sessionId: 'A7D88AE69687E58D9A00',
  cookie: true,
  loggedIn: true,
  configStarted: false,
  soapVersion: 3,
  loginMethod: 2,
  getAttachedDevicesMethod: 2,
  checkNewFirmwareMethod: 1,
  guestWifiMethod: { set24_1: undefined, get50_1: 1, set50_1: undefined },
  lastResponse: '...',
  queue: SmartQueue {
    queue: Map(1) { 1626982030027 => [Object] },
    overheat: 1626982009312,
    pending: true,
    params: {
      default: [Object],
      rules: [Object],
      overall: [Object],
      retryTime: 2,
      ignoreOverallOverheat: true
    },
    heatPart: 100
  }
}
t = 20.762
test finished with 20 errors

**Comment by gruijter** [comment]
I hope a new firmware and/or the latest nethear package has solved your issue. Pls reopen if you think I can do anything.
