### ISSUE TITLE
log in error

### ISSUE THREAD

**Issue by djungelola** [gruijter/netgear.js#17]
when running the test i get login errors. Using MR60.

Testing now. Hang on.....
========== STARTING TEST ==========
Node version: v8.10.0
Netgear package version: 4.3.3
OS: linux 4.4.0-19041-Microsoft
t = 0
trying to auto discover Netgear routers...
[ { Firmware: 'V1.0.6.116',
    RegionTag: 'MR60_WW',
    Region: 'ww',
    Model: 'MR60',
    InternetConnectionStatus: 'Up',
    OpenDNSEnabled: '0',
    SOAPVersion: '3.78',
    ReadyShareSupportedLevel: '0',
    XCloudSupported: '1',
    LoginMethod: '2.0',
    DeviceMode: '0',
    isBlankState: '0',
    SOAP_HTTPs_Port: '443',
    host: '192.168.1.1',
    port: 80 },
  { Firmware: 'V1.0.6.116',
    RegionTag: 'MS60_WW',
    Region: 'ww',
    Model: 'MS60',
    InternetConnectionStatus: 'Down',
    ParentalControlSupported: '0',
    CircleEnabled: '0',
    OpenDNSEnabled: '0',
    SOAPVersion: '3.58',
    ReadyShareSupportedLevel: '25',
    XCloudSupported: '0',
    LoginMethod: '2.0',
    DeviceMode: '0',
    SOAP_HTTPs_Port: '443',
    host: '192.168.1.19',
    port: 80 },
  { Firmware: 'V1.0.6.116',
    RegionTag: 'MS60_WW',
    Region: 'ww',
    Model: 'MS60',
    InternetConnectionStatus: 'Up',
    ParentalControlSupported: '0',
    CircleEnabled: '0',
    OpenDNSEnabled: '0',
    SOAPVersion: '3.58',
    ReadyShareSupportedLevel: '25',
    XCloudSupported: '0',
    LoginMethod: '2.0',
    DeviceMode: '0',
    SOAP_HTTPs_Port: '443',
    host: '192.168.1.33',
    port: 80 } ]
t = 3.157
trying to login using method 1...
method 1 failed.
trying to login using method 2...
method 2 failed.
trying to login using auto method...
{ Error: getaddrinfo EAI_AGAIN routerlogin.net:80
    at Object._errnoException (util.js:1022:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
  code: 'EAI_AGAIN',
  errno: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'routerlogin.net',
  host: 'routerlogin.net',
  port: 80 }
NetgearRouter {
  host: 'routerlogin.net',
  port: undefined,
  tls: false,
  username: 'admin',
  password: '*****',
  timeout: 18000,
  sessionId: 'A7D88AE69687E58D9A00',
  cookie: undefined,
  loggedIn: false,
  configStarted: false,
  soapVersion: 3,
  loginMethod: 2,
  getAttachedDevicesMethod: undefined,
  checkNewFirmwareMethod: undefined,
  guestWifiMethod: { set24_1: undefined, get50_1: undefined, set50_1: undefined },
  lastResponse:
   { Error: getaddrinfo EAI_AGAIN routerlogin.net:80
    at Object._errnoException (util.js:1022:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
     code: 'EAI_AGAIN',
     errno: 'EAI_AGAIN',
     syscall: 'getaddrinfo',
     hostname: 'routerlogin.net',
     host: 'routerlogin.net',
     port: 80 },
  queue:
   SmartQueue {
     queue: Map {},
     overheat: 1636012764586,
     pending: false,
     params:
      { default: [Object],
        rules: [Object],
        overall: [Object],
        retryTime: 2,
        ignoreOverallOverheat: true },
     heatPart: 100 } }

Anything i do wrong?

/Ola

**Comment by gruijter** [comment]
getaddrinfo EAI_AGAIN

Suggests a problem with your DNS. Check your DNS settings.
Secondly you might want to upgrade your node to a more recent version. Node 8.10 is getting old...

**Comment by djungelola** [comment]
> Suggests a problem with your DNS. Check your DNS settings.

Not really sure what to check. Cant do much about the DNS in the GUI.

/Ola

**Comment by djungelola** [comment]
> > Suggests a problem with your DNS. Check your DNS settings.
> 
> Not really sure what to check. Cant do much about the DNS in the GUI.
> 
> /Ola

Wrong password. Easy as that :-)
