### ISSUE TITLE
Return info from RST_statistic.htm

### ISSUE THREAD

**Issue by derekoharrow** [gruijter/netgear.js#19]
The Orbi routers have a lot of useful connection info available using the URL /RST_statistic.htm

Is it possible to return this info too.

In my particular case I want to be able to get the WAN port speed (e.g. 1000M/Full) as occassionally it drops down to 100M at which point I need to reboot the Orbi.

Thanks

**Comment by gruijter** [comment]
Do you have a screenshot of the info you are looking for?

**Comment by derekoharrow** [comment]
Yes, see here https://www.reddit.com/r/homeassistant/comments/t10vvp/scarping_orbi_info/

**Comment by gruijter** [comment]
I dont have a soap command for this data. I also checked the HTML, but not a clue what the soap call would be.

If you can figure out the soap command Im definitely willing to implement it.
