### ISSUE TITLE
Unable to login for Firmware V1.0.9.64_10.2.64 for Netgear R7000

### ISSUE THREAD

**Issue by arunsudhakar** [gruijter/netgear.js#8]
Hi,

The script was working fine on a much older firmware . But I'd to upgrade to the newer firmware after which the script fails to login. This is what i get.

Error: Failed to login
    at NetgearRouter.login (/root/node_modules/netgear/netgear.js:174:25)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

I tried logging in using different browsers with the password I've provided in the file and it works.

Any idea what the issue could be?

**Comment by arunsudhakar** [comment]
Actually if i change the password of defaultPassword in netgear.js it works. So I suspect the default password is not being overridden

**Comment by gruijter** [comment]
Could you run a test with the original package, and post the result here? ( npm test yourPassword )

**Comment by arunsudhakar** [comment]
I found out the issue. It was my mistake . In the login command I was giving the password without specifying what the argument was. ie instead of router.login(password="XXXX"); i was giving router.login("XXXX");

It works properly after giving that.  I shall proceed to close the issue and thanks for this awesome package ... 👍 keep up the good work

**Comment by arunsudhakar** [comment]
I found out the issue. It was my mistake . In the login command I was giving the password without specifying what the argument was. ie instead of router.login(password="XXXX"); i was giving router.login("XXXX");

It works properly after giving that. I shall proceed to close the issue and thanks for this awesome package ... 👍 keep up the good work
